{{- if .Values.hub.caBundle -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kfleet-agent.fullname" . }}-hub-ca
  labels:
    {{- include "kfleet-agent.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ required "hub.caBundle must be PEM-encoded certificate data" .Values.hub.caBundle | b64enc }}
{{- end }}