{{- if .Values.hub.caBundle -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kfleet-agent.fullname" . }}-hub-ca
  labels:
    {{- include "kfleet-agent.labels" . | nindent 4 }}
type: Opaque
data:
  # ca.crt holds PEM-encoded certificate(s) that verify the hub's TLS certificate.
  ca.crt: {{ .Values.hub.caBundle | b64enc }}
{{- end }}
