apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kfleet-agent.fullname" . }}
  labels:
    {{- include "kfleet-agent.labels" . | nindent 4 }}
type: Opaque
data:
  hub-token: {{ .Values.hub.token | b64enc | quote }}
