apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kfleet-hub.fullname" . }}
  labels:
    {{- include "kfleet-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  registration-token: {{ .Values.registration.token | quote }}
  alert-webhook-secret: {{ .Values.alerts.webhook.secret | quote }}
  bootstrap-admin-username: {{ .Values.auth.bootstrapAdmin.username | quote }}
  bootstrap-admin-email: {{ .Values.auth.bootstrapAdmin.email | quote }}
  bootstrap-admin-password: {{ .Values.auth.bootstrapAdmin.password | quote }}
