apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kfleet-hub.fullname" . }}
  labels:
    {{- include "kfleet-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  registration-token: {{ .Values.registration.token | quote }}
  alert-webhook-secret: {{ .Values.alerts.webhook.secret | quote }}
